[tools]
go = 'latest'

[tasks]

install = [
    "brew install protobuf",
    "go install google.golang.org/protobuf/cmd/protoc-gen-go@latest",
    "go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest",
    "go install github.com/air-verse/air@latest"
]

dev = "air"